- job_name: 'test'
  # Override the global default and scrape targets from this job every 5 seconds.
  scrape_interval: 5m
  metrics_path: '/metrics'
  static_configs:
    - targets: ['test.example.com']
      labels:
        group: 'dev'
