kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-operator-gluster-pvc 
  namespace: monitoring 
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
