apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-operator-gluster-pv
  namespace: monitoring
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  glusterfs:
    endpoints: "glusterfs-cluster-monitoring"
    path: "k8s-volume/prometheus-operator/grafana-data"
    readOnly: false
